# convention : version names : lower-kebab-case | libraries : just name(not module name) | plugin : whole plugin name

[versions]
#noinspection UnusedVersionCatalogEntry
appinfo-packagename = "io.github.curioustools.curiousnews" #noinspection UnusedVersionCatalogEntry
appinfo-buildtools = "36.0.0" #noinspection UnusedVersionCatalogEntry
appinfo-compileSdk = "36" #noinspection UnusedVersionCatalogEntry
appinfo-targetSdk = "36" #noinspection UnusedVersionCatalogEntry
appinfo-minSdk = "28" #noinspection UnusedVersionCatalogEntry
appinfo-versionCode = "1" #noinspection UnusedVersionCatalogEntry
appinfo-versionName = "1.0.0" #noinspection UnusedVersionCatalogEntry
appinfo-targetRunner = "androidx.test.runner.AndroidJUnitRunner"#noinspection UnusedVersionCatalogEntry
appinfo-jvm = "22"

#core-arch : AGP, kotlin, KSP
app-compat = "1.7.1" #needed?
core-ktx = "1.17.0"
kotlinx-serialisation-core = "1.9.0"
exoplayerMedia3 = "1.8.0"
webkit = "1.14.0"
plugin-kotlin = "2.2.21"
plugin-agp = "8.13.0" #should be compatible with android studio and gradle wrapper version : https://developer.android.com/build/releases/gradle-plugin#updating-gradle
plugin-ksp = "2.3.0" #should be compatible with kotlin version : https://developer.android.com/build/migrate-to-ksp#add-ksp


#core-arch : hilt
plugin-hilt = "2.57.2"

#core-ui: lifecycle
lifecycle-runtime-ktx = "2.9.4"

#core-ui : navigation
nav3-core = "1.0.0-beta01"
nav3-lifecycle-viewmodel = "2.10.0-beta01"

#core-ui : compose-bom, navigation
compose-activity = "1.11.0"
compose-bom = "2025.10.01"
compose-material-icons-core = "1.7.8"
compose-material3-adaptive-nav3 = "1.3.0-alpha03"
compose-navigation = "2.9.5"
compose-text-google-fonts = "1.9.4"
compose-hilt-navigation = "1.3.0"

#core-ui-networking : coil/glide
glide = "5.0.5"
coil = "3.3.0"

#networking: retrofit,okhttp,gson,timber
okhttp = "5.3.0"
retrofit = "3.0.0"
gson = "2.13.2"
timber = "5.0.1"
stetho = "1.6.0"

#networking: AWS, Firebase
firebase-plugin-crashlytics = "3.0.6"
firebase-plugin-perf = "2.0.2"

google-services = "4.4.4"

#ui libs
jsoup = "1.21.2"
browser = "1.9.0"

#testing :
junit = "4.13.2"
android-junit = "1.3.0"
espresso-core = "3.7.0"



[libraries]
#core-arch : AGP, kotlin, KSP
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialisation-core" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialisation-core" }

#core-arch : hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "plugin-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "plugin-hilt" }

#core-ui: activity,lifecycle, material
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

#core-ui navigation
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3-core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3-core" }
androidx-navigation3-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3-lifecycle-viewmodel" }


#core-ui : compose-bom, navigation
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material-icons-core" }
compose-material3 = { group = "androidx.compose.material3", name = "material3"}
compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
compose-material3-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3" ,version.ref= "compose-material3-adaptive-nav3" }
compose-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "compose-hilt-navigation" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose-hilt-navigation" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-text = { group = "androidx.compose.ui", name = "ui-text" }
compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose-text-google-fonts" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#networking : coil/glide
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

#networking: retrofit,okhttp,gson,timber
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
stetho = { group = "com.facebook.stetho", name = "stetho", version.ref = "stetho" }
stetho-okhttp3 = { group = "com.facebook.stetho", name = "stetho-okhttp3", version.ref = "stetho" }



#ui libs
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
androidx-exoplayer-media3 = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayerMedia3" }
androidx-exoplayer-media3-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayerMedia3" }
androidx-exoplayer-media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "exoplayerMedia3" }
androidx-exoplayer-media3-session = { module = "androidx.media3:media3-session", version.ref = "exoplayerMedia3" }
androidx-exoplayer-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayerMedia3" }
compose-exoplayer-media3-ui = { module = "androidx.media3:media3-ui-compose", version.ref = "exoplayerMedia3" }

#testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "android-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }


[plugins]
#android : application/library
com-android-application = { id = "com.android.application", version.ref = "plugin-agp" }
com-android-library = { id = "com.android.library", version.ref = "plugin-agp" }

#jetbrains : kotlin,compose,parcelise,serialize
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "plugin-kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "plugin-kotlin" }

#google : ksp,hilt,google-services,firebase
com-google-devtools-ksp = {id="com.google.devtools.ksp", version.ref = "plugin-ksp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "plugin-hilt" }

